"""APScheduler jobs for the ASX200 predictor.

The daily job runs once per ASX trading day around 13:35 AEST (±15 minutes).
An optional overnight update runs after the US close (~06:30 AEST).
"""

from __future__ import annotations

from datetime import date

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger

from asx200_mag_predictor.config import Settings, get_settings
from asx200_mag_predictor.data.fetchers import DataFetcher
from asx200_mag_predictor.logging_config import get_logger
from asx200_mag_predictor.scoring.engine import ScoringEngine
from asx200_mag_predictor.scoring.features import build_features
from asx200_mag_predictor.storage.models import init_db
from asx200_mag_predictor.storage.repository import Repository
from asx200_mag_predictor.timezone import SYDNEY, now_sydney

logger = get_logger(__name__)


class DailyJob:
    """Encapsulates the daily prediction run."""

    def __init__(self, settings: Settings | None = None):
        self.settings = settings or get_settings()
        self.engine = ScoringEngine(self.settings)
        self.fetcher = DataFetcher(self.settings)
        self.repo = Repository()

    def run(self, source: str = "scheduler") -> dict:
        """Fetch data, build features, predict, and store."""
        now = now_sydney()
        if not self._is_asx_trading_day(now.date()):
            logger.info("Skipping run: %s is not an ASX trading day", now.date())
            return {"status": "skipped", "reason": "non-trading-day"}

        try:
            raw = self.fetcher.fetch_all()
            features, flags = build_features(raw)
            prediction = self.engine.predict(features, flags)
            prediction.notes.append(f"Generated by {source} at {now.isoformat()}")
            prediction_id = self.repo.save_prediction(prediction)
            logger.info("Saved prediction %s for %s", prediction_id, prediction.prediction_for_date)
            return {"status": "ok", "prediction_id": prediction_id, "bucket": prediction.bucket}
        except Exception as exc:  # noqa: BLE001
            logger.exception("Daily prediction job failed")
            return {"status": "error", "error": str(exc)}

    def overnight_update(self) -> dict:
        """Optional US-close refresh: fetch and store an updated snapshot."""
        # For now, run the same prediction pipeline and overwrite with a note.
        return self.run(source="overnight-update")

    def _is_asx_trading_day(self, d: date) -> bool:
        """Basic check: weekday + not a fixed holiday."""
        if d.weekday() >= 5:
            return False
        # Skip fixed public holidays (simplified; use a real calendar in prod)
        from asx200_mag_predictor.timezone import asx_holiday_list

        holidays = asx_holiday_list(d.year)
        return d.strftime("%Y-%m-%d") not in holidays


def start_scheduler(settings: Settings | None = None) -> BackgroundScheduler:
    """Start the APScheduler background scheduler."""
    settings = settings or get_settings()
    init_db(settings)

    scheduler = BackgroundScheduler(timezone=str(SYDNEY))
    job = DailyJob(settings)

    if settings.schedule_daily:
        hour, minute = settings.daily_run_time.split(":")
        scheduler.add_job(
            job.run,
            trigger=CronTrigger(
                hour=int(hour),
                minute=int(minute),
                timezone=str(SYDNEY),
                jitter=900,  # random delay up to ±15 min around the target
            ),
            id="daily_prediction",
            name="ASX200 daily magnitude prediction",
            replace_existing=True,
        )

    if settings.us_close_update:
        hour, minute = settings.us_close_run_time.split(":")
        scheduler.add_job(
            job.overnight_update,
            trigger=CronTrigger(
                hour=int(hour),
                minute=int(minute),
                timezone=str(SYDNEY),
                jitter=300,
            ),
            id="overnight_update",
            name="Overnight US-close update",
            replace_existing=True,
        )

    scheduler.start()
    return scheduler


def main() -> None:
    """Run the scheduler in the foreground."""
    settings = get_settings()
    scheduler = start_scheduler(settings)
    logger.info("Scheduler started; jobs: %s", scheduler.get_jobs())
    try:
        # Keep the process alive
        while True:
            __import__("time").sleep(1)
    except (KeyboardInterrupt, SystemExit):
        scheduler.shutdown()


if __name__ == "__main__":
    main()
